// DO NOT EDIT THIS FILE !!!
// Represents a connection between two islands a and b which could collapse with probability p
public class Bridge {
    double p;
    int a;
    int b;

    Bridge(double p, int a, int b){
        this.p = p;
        this.a = a;
        this.b = b;
    }
}